import {useState, createContext} from 'react';
// import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
import Header from "./header.js";
import NavBar from "./navBar.js";
import Content from "./content.js";
import Footer from "./footer.js";

const inter = Inter({ subsets: ["latin"] });

export const NavBarContext = createContext("");

export default function Home() {
  const [content, setContent] = useState("Home");
  return (
    <>
      {/* <Head> */}
      {/* <head>
        <title>Expedition Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      {/* </Head> */}
      {/* </head> */}
      <main>
        <div class="row m-2">
          <div class="col-md-10 border border-warning"><Header /></div>
        </div>
        <div class="row m-2">
          <NavBarContext.Provider value={{content, setContent}}>
            <div class="col-md-2 border border-warning ml-3">
              <NavBar />
            </div>
            <div class="col-md-8 border border-warning">            
              <Content />
            </div>  
          </NavBarContext.Provider>
        </div>
        <div class="row m-2">
          <div class="col-md-10 border border-warning">
            <Footer />
          </div>
        </div>
      </main>
    </>
  );
}
